%% define path to data
data_path = './RawData/Idealized_Reference_Actuated_System_4comp/';

%% import data with parameter sampling over 4 orders of magnitude
stats_fname_1 = strcat(data_path,...
    'Idealized_Reference_Actuated_1_4comp_STATISTICS.bin');
stats_1 = read_AIF_four_components_statistics(stats_fname_1);
params_fname_1 = strcat(data_path,...
    'Idealized_Reference_Actuated_1_4comp_PARAMETERS.bin');
params_1 = read_AIF_four_components_parameters(params_fname_1);

stats_fname_2 = strcat(data_path,...
    'Idealized_Reference_Actuated_2_4comp_STATISTICS.bin');
stats_2 = read_AIF_four_components_statistics(stats_fname_2);
params_fname_2 = strcat(data_path,...
    'Idealized_Reference_Actuated_2_4comp_PARAMETERS.bin');
params_2 = read_AIF_four_components_parameters(params_fname_2);

stats_fname_3 = strcat(data_path,...
    'Idealized_Reference_Actuated_3_4comp_STATISTICS.bin');
stats_3 = read_AIF_four_components_statistics(stats_fname_3);
params_fname_3 = strcat(data_path,...
    'Idealized_Reference_Actuated_3_4comp_PARAMETERS.bin');
params_3 = read_AIF_four_components_parameters(params_fname_3);

stats_fname_4 = strcat(data_path,...
    'Idealized_Reference_Actuated_4_4comp_STATISTICS.bin');
stats_4 = read_AIF_four_components_statistics(stats_fname_4);
params_fname_4 = strcat(data_path,...
    'Idealized_Reference_Actuated_4_4comp_PARAMETERS.bin');
params_4 = read_AIF_four_components_parameters(params_fname_4);

stats_fname_5 = strcat(data_path,...
    'Idealized_Reference_Actuated_5_4comp_STATISTICS.bin');
stats_5 = read_AIF_four_components_statistics(stats_fname_5);
params_fname_5 = strcat(data_path,...
    'Idealized_Reference_Actuated_5_4comp_PARAMETERS.bin');
params_5 = read_AIF_four_components_parameters(params_fname_5);

stats_fname_6 = strcat(data_path,...
    'Idealized_Reference_Actuated_6_4comp_STATISTICS.bin');
stats_6 = read_AIF_four_components_statistics(stats_fname_6);
params_fname_6 = strcat(data_path,...
    'Idealized_Reference_Actuated_6_4comp_PARAMETERS.bin');
params_6 = read_AIF_four_components_parameters(params_fname_6);

stats_fname_7 = strcat(data_path,...
    'Idealized_Reference_Actuated_7_4comp_STATISTICS.bin');
stats_7 = read_AIF_four_components_statistics(stats_fname_7);
params_fname_7 = strcat(data_path,...
    'Idealized_Reference_Actuated_7_4comp_PARAMETERS.bin');
params_7 = read_AIF_four_components_parameters(params_fname_7);

stats_fname_8 = strcat(data_path,...
    'Idealized_Reference_Actuated_8_4comp_STATISTICS.bin');
stats_8 = read_AIF_four_components_statistics(stats_fname_8);
params_fname_8 = strcat(data_path,...
    'Idealized_Reference_Actuated_8_4comp_PARAMETERS.bin');
params_8 = read_AIF_four_components_parameters(params_fname_8);

stats_fname_9 = strcat(data_path,...
    'Idealized_Reference_Actuated_9_4comp_STATISTICS.bin');
stats_9 = read_AIF_four_components_statistics(stats_fname_9);
params_fname_9 = strcat(data_path,...
    'Idealized_Reference_Actuated_9_4comp_PARAMETERS.bin');
params_9 = read_AIF_four_components_parameters(params_fname_9);

stats_fname_10 = strcat(data_path,...
    'Idealized_Reference_Actuated_10_4comp_STATISTICS.bin');
stats_10 = read_AIF_four_components_statistics(stats_fname_10);
params_fname_10 = strcat(data_path,...
    'Idealized_Reference_Actuated_10_4comp_PARAMETERS.bin');
params_10 = read_AIF_four_components_parameters(params_fname_10);

stats_2_fname_1 = strcat(data_path,...
    'Idealized_Reference_Actuated_11_4comp_STATISTICS.bin');
stats_2_1 = read_AIF_four_components_statistics(stats_2_fname_1);
params_2_fname_1 = strcat(data_path,...
    'Idealized_Reference_Actuated_11_4comp_PARAMETERS.bin');
params_2_1 = read_AIF_four_components_parameters(params_2_fname_1);

stats_2_fname_2 = strcat(data_path,...
    'Idealized_Reference_Actuated_12_4comp_STATISTICS.bin');
stats_2_2 = read_AIF_four_components_statistics(stats_2_fname_2);
params_2_fname_2 = strcat(data_path,...
    'Idealized_Reference_Actuated_12_4comp_PARAMETERS.bin');
params_2_2 = read_AIF_four_components_parameters(params_2_fname_2);

stats_2_fname_3 = strcat(data_path,...
    'Idealized_Reference_Actuated_13_4comp_STATISTICS.bin');
stats_2_3 = read_AIF_four_components_statistics(stats_2_fname_3);
params_2_fname_3 = strcat(data_path,...
    'Idealized_Reference_Actuated_13_4comp_PARAMETERS.bin');
params_2_3 = read_AIF_four_components_parameters(params_2_fname_3);

stats_2_fname_4 = strcat(data_path,...
    'Idealized_Reference_Actuated_14_4comp_STATISTICS.bin');
stats_2_4 = read_AIF_four_components_statistics(stats_2_fname_4);
params_2_fname_4 = strcat(data_path,...
    'Idealized_Reference_Actuated_14_4comp_PARAMETERS.bin');
params_2_4 = read_AIF_four_components_parameters(params_2_fname_4);

stats_2_fname_5 = strcat(data_path,...
    'Idealized_Reference_Actuated_15_4comp_STATISTICS.bin');
stats_2_5 = read_AIF_four_components_statistics(stats_2_fname_5);
params_2_fname_5 = strcat(data_path,...
    'Idealized_Reference_Actuated_15_4comp_PARAMETERS.bin');
params_2_5 = read_AIF_four_components_parameters(params_2_fname_5);

stats_2_fname_6 = strcat(data_path,...
    'Idealized_Reference_Actuated_16_4comp_STATISTICS.bin');
stats_2_6 = read_AIF_four_components_statistics(stats_2_fname_6);
params_2_fname_6 = strcat(data_path,...
    'Idealized_Reference_Actuated_16_4comp_PARAMETERS.bin');
params_2_6 = read_AIF_four_components_parameters(params_2_fname_6);

stats_2_fname_7 = strcat(data_path,...
    'Idealized_Reference_Actuated_17_4comp_STATISTICS.bin');
stats_2_7 = read_AIF_four_components_statistics(stats_2_fname_7);
params_2_fname_7 = strcat(data_path,...
    'Idealized_Reference_Actuated_17_4comp_PARAMETERS.bin');
params_2_7 = read_AIF_four_components_parameters(params_2_fname_7);

stats_2_fname_8 = strcat(data_path,...
    'Idealized_Reference_Actuated_18_4comp_STATISTICS.bin');
stats_2_8 = read_AIF_four_components_statistics(stats_2_fname_8);
params_2_fname_8 = strcat(data_path,...
    'Idealized_Reference_Actuated_18_4comp_PARAMETERS.bin');
params_2_8 = read_AIF_four_components_parameters(params_2_fname_8);

stats_2_fname_9 = strcat(data_path,...
    'Idealized_Reference_Actuated_19_4comp_STATISTICS.bin');
stats_2_9 = read_AIF_four_components_statistics(stats_2_fname_9);
params_2_fname_9 = strcat(data_path,...
    'Idealized_Reference_Actuated_19_4comp_PARAMETERS.bin');
params_2_9 = read_AIF_four_components_parameters(params_2_fname_9);

stats_2_fname_10 = strcat(data_path,...
    'Idealized_Reference_Actuated_20_4comp_STATISTICS.bin');
stats_2_10 = read_AIF_four_components_statistics(stats_2_fname_10);
params_2_fname_10 = strcat(data_path,...
    'Idealized_Reference_Actuated_20_4comp_PARAMETERS.bin');
params_2_10 = read_AIF_four_components_parameters(params_2_fname_10);

% aggregate data 
params = struct;
fn = fieldnames(params_1);
for i = 1:numel(fn)
    params.(fn{i}) = [params_1.(fn{i});...
        params_2.(fn{i});params_3.(fn{i});...
        params_4.(fn{i});params_5.(fn{i});...
        params_6.(fn{i});params_7.(fn{i});...
		params_8.(fn{i});params_9.(fn{i});...
		params_10.(fn{i});...
        params_2_1.(fn{i});...
        params_2_2.(fn{i});params_2_3.(fn{i});...
        params_2_4.(fn{i});params_2_5.(fn{i});...
        params_2_6.(fn{i});params_2_7.(fn{i});...
		params_2_8.(fn{i});params_2_9.(fn{i});...
		params_2_10.(fn{i})];
end
stats = struct;
fn = fieldnames(stats_1);
for i = 1:numel(fn)
    stats.(fn{i}) = [stats_1.(fn{i});...
        stats_2.(fn{i});stats_3.(fn{i});...
        stats_4.(fn{i});stats_5.(fn{i});...
        stats_6.(fn{i});stats_7.(fn{i});...
		stats_8.(fn{i});stats_9.(fn{i});...
		stats_10.(fn{i});...
        stats_2_1.(fn{i});...
        stats_2_2.(fn{i});stats_2_3.(fn{i});...
        stats_2_4.(fn{i});stats_2_5.(fn{i});...
        stats_2_6.(fn{i});stats_2_7.(fn{i});...
		stats_2_8.(fn{i});stats_2_9.(fn{i});...
		stats_2_10.(fn{i})];
end

fprintf(strcat(num2str(numel(params.mu)),...
    ' parameter sets total with parameter sampling',...
    ' over four orders of magnitude. \n'))

%% check flux and covariance balance 

% 2% threshold
FB = check_flux_balance_AIF_four_components(stats,...
    params, 2/100); 
% 5% threshold
CB = check_covariance_balance_AIF_four_components(stats,...
    params, 5/100); 
inds = FB & CB;
fprintf(strcat(num2str(sum(inds)),...
    ' parameter sets pass flux and covariance balance',...
    ' with parameter sampling over two orders of magnitude.',...
    '\n'))

%% subset data based on flux and covariance balance tests
fn = fieldnames(params);
for i = 1:numel(fn)
    field_vals = params.(fn{i});
    params.(fn{i}) = field_vals(inds);
end
fn = fieldnames(stats);
for i = 1:numel(fn)
    field_vals = stats.(fn{i});
    stats.(fn{i}) = field_vals(inds);
end

%% check for open-loop limit outliers
OL_CV = sqrt((1./stats.Z_avg) + (1./stats.W_avg)...
    .*(1./params.beta_w)./((1./params.beta_w) + (1./params.beta_z)));
num_OL_outliers = ...
    sum(sqrt(stats.Z_var./(stats.Z_avg.^2)) < OL_CV);
fprintf(strcat(num2str(sum(num_OL_outliers)),...
    ' CV values below open-loop levels for data with parameter sampling',...
    ' over four orders of magnitude. \n'))

%%
fs_ax = 18;
lw_plot = 3;
ms = 12;

OL_CV = sqrt((1./stats.Z_avg) + (1./stats.W_avg)...
    .*(1./params.beta_w)./((1./params.beta_w) + (1./params.beta_z)));

CL_CV = sqrt(stats.Z_var./(stats.Z_avg.^2));

x = linspace(0, max(OL_CV)+0.1, 1e5);
figure;
scatter(OL_CV, CL_CV, ms, 'filled', 'black')
hold on
plot(x,x, 'LineWidth', lw_plot, 'Color','Red')
xlim([0,25])
ylim([0,25])aa
xlabel('\textbf{Open-loop noise} \boldmath$\sqrt{\frac{1}{\langle x \rangle} + \frac{\tau_w}{\tau_x + \tau_w}\frac{1}{\langle w \rangle}}$',...
    'Interpreter', 'Latex', 'fontsize', fs_ax)
ylabel('\textbf{Closed-loop noise} \boldmath$\mathrm{CV}_x$',...
    'Interpreter', 'Latex', 'fontsize', fs_ax)
exportgraphics(gcf, './Figures/SI_4comp_rAIF_noisepenalty.pdf','ContentType','vector')

%%
[m, i] = max((OL_CV - CL_CV)./OL_CV)